name: bioinfo
channels:
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=openblas
  - bottleneck=1.3.7=py38ha9d4c09_0
  - bwa=0.7.17=h5bf99c6_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.3.11=h06a4308_0
  - curl=7.69.1=hbc83047_0
  - expat=2.6.2=h6a678d5_0
  - fastqc=0.12.1=hdfd78af_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h4a9f257_0
  - htslib=1.9=ha228f0b_7
  - icu=58.2=he6710b0_3
  - krb5=1.17.1=h173b8e3_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcurl=7.69.1=h20c2e04_0
  - libdeflate=1.0=h14c3975_1
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxml2=2.10.3=hcbfbd50_0
  - ncurses=6.1=he6710b0_1
  - numexpr=2.8.4=py38hd2a5715_1
  - numpy=1.24.3=py38hf838250_0
  - numpy-base=1.24.3=py38h1e6e340_0
  - openjdk=8.0.152=h7b6447c_3
  - openssl=1.1.1w=h7f8727e_0
  - pandas=2.0.3=py38h1128e8f_0
  - perl=5.34.0=h5eee18b_1
  - pip=24.0=py38h06a4308_0
  - python=3.8.1=h0371630_1
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py38h06a4308_0
  - readline=7.0=h7b6447c_5
  - samtools=1.9=h10a08f8_12
  - setuptools=69.5.1=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py38h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
prefix: /home/michaelswift/miniconda3/envs/bioinfo
